# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\python\spider\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 600)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_log = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_log.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.txt_log.setFont(font)
        self.txt_log.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_log.setReadOnly(False)
        self.txt_log.setPlainText("")
        self.txt_log.setObjectName("txt_log")
        self.gridLayout_2.addWidget(self.txt_log, 0, 1, 1, 1)
        self.txt_email = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_email.setMinimumSize(QtCore.QSize(230, 0))
        self.txt_email.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.txt_email.setFont(font)
        self.txt_email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_email.setReadOnly(True)
        self.txt_email.setPlainText("")
        self.txt_email.setObjectName("txt_email")
        self.gridLayout_2.addWidget(self.txt_email, 0, 0, 1, 1)
        self.lbl_email = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout_2.addWidget(self.lbl_email, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_start.setEnabled(True)
        self.btn_start.setCheckable(False)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_resume = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_resume.setObjectName("btn_resume")
        self.horizontalLayout.addWidget(self.btn_resume)
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.lbl_timer = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_timer.setObjectName("lbl_timer")
        self.horizontalLayout.addWidget(self.lbl_timer)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.txt_pageSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_pageSize.setObjectName("txt_pageSize")
        self.gridLayout_5.addWidget(self.txt_pageSize, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 3, 1, 1)
        self.txt_threadNum = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_threadNum.setObjectName("txt_threadNum")
        self.gridLayout_5.addWidget(self.txt_threadNum, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 8, 1, 1)
        self.txt_workSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_workSize.setObjectName("txt_workSize")
        self.gridLayout_5.addWidget(self.txt_workSize, 0, 9, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 13, 1, 1)
        self.txt_pageDelay = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_pageDelay.setObjectName("txt_pageDelay")
        self.gridLayout_5.addWidget(self.txt_pageDelay, 0, 14, 1, 1)
        self.chk_searchList = QtWidgets.QCheckBox(self.groupBox_4)
        self.chk_searchList.setEnabled(True)
        self.chk_searchList.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_searchList.setChecked(False)
        self.chk_searchList.setObjectName("chk_searchList")
        self.gridLayout_5.addWidget(self.chk_searchList, 0, 7, 1, 1)
        self.txt_searchDelay = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_searchDelay.setObjectName("txt_searchDelay")
        self.gridLayout_5.addWidget(self.txt_searchDelay, 0, 6, 1, 1)
        self.combo_source = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_source.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_source.setObjectName("combo_source")
        self.combo_source.addItem("")
        self.gridLayout_5.addWidget(self.combo_source, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 0, 1, 6)
        self.btn_saveKeyword = QtWidgets.QPushButton(self.groupBox)
        self.btn_saveKeyword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_saveKeyword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_saveKeyword.setObjectName("btn_saveKeyword")
        self.gridLayout_3.addWidget(self.btn_saveKeyword, 6, 0, 1, 1)
        self.btn_search_link = QtWidgets.QPushButton(self.groupBox)
        self.btn_search_link.setEnabled(True)
        self.btn_search_link.setObjectName("btn_search_link")
        self.gridLayout_3.addWidget(self.btn_search_link, 6, 5, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txt_pattern = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txt_pattern.setMinimumSize(QtCore.QSize(230, 0))
        self.txt_pattern.setMaximumSize(QtCore.QSize(230, 16777215))
        self.txt_pattern.setBackgroundVisible(False)
        self.txt_pattern.setCenterOnScroll(False)
        self.txt_pattern.setObjectName("txt_pattern")
        self.gridLayout_4.addWidget(self.txt_pattern, 2, 2, 1, 1)
        self.txt_keyword_flag = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txt_keyword_flag.setMinimumSize(QtCore.QSize(230, 0))
        self.txt_keyword_flag.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.txt_keyword_flag.setFont(font)
        self.txt_keyword_flag.setReadOnly(False)
        self.txt_keyword_flag.setPlainText("")
        self.txt_keyword_flag.setObjectName("txt_keyword_flag")
        self.gridLayout_4.addWidget(self.txt_keyword_flag, 2, 1, 1, 1)
        self.txt_keyword = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txt_keyword.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_keyword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.txt_keyword.setFont(font)
        self.txt_keyword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_keyword.setReadOnly(False)
        self.txt_keyword.setPlainText("")
        self.txt_keyword.setObjectName("txt_keyword")
        self.gridLayout_4.addWidget(self.txt_keyword, 2, 0, 1, 1)
        self.title_keyword = QtWidgets.QLabel(self.groupBox_5)
        self.title_keyword.setObjectName("title_keyword")
        self.gridLayout_4.addWidget(self.title_keyword, 0, 0, 1, 1)
        self.title_keywordFlag = QtWidgets.QLabel(self.groupBox_5)
        self.title_keywordFlag.setObjectName("title_keywordFlag")
        self.gridLayout_4.addWidget(self.title_keywordFlag, 0, 1, 1, 1)
        self.combo_pattern = QtWidgets.QComboBox(self.groupBox_5)
        self.combo_pattern.setEditable(False)
        self.combo_pattern.setFrame(True)
        self.combo_pattern.setObjectName("combo_pattern")
        self.combo_pattern.addItem("")
        self.combo_pattern.addItem("")
        self.gridLayout_4.addWidget(self.combo_pattern, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 0, 1, 6)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spider"))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出信息"))
        self.txt_log.setPlaceholderText(_translate("MainWindow", "操作日志输出窗口"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "搜索结果输出窗口"))
        self.lbl_email.setText(_translate("MainWindow", "已获取 0 条数据"))
        self.btn_start.setText(_translate("MainWindow", "重新开始"))
        self.btn_resume.setText(_translate("MainWindow", "继续运行"))
        self.btn_stop.setText(_translate("MainWindow", "停止"))
        self.lbl_timer.setText(_translate("MainWindow", "00:00:00"))
        self.groupBox.setTitle(_translate("MainWindow", "设置选项"))
        self.label.setText(_translate("MainWindow", "搜索最大页数"))
        self.txt_pageSize.setText(_translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "最大线程数"))
        self.txt_threadNum.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "深度搜索队列"))
        self.txt_workSize.setText(_translate("MainWindow", "20"))
        self.label_3.setText(_translate("MainWindow", "搜索列表延时"))
        self.label_4.setText(_translate("MainWindow", "深度搜索延时"))
        self.txt_pageDelay.setText(_translate("MainWindow", "0"))
        self.chk_searchList.setText(_translate("MainWindow", "是否深度搜索"))
        self.txt_searchDelay.setText(_translate("MainWindow", "0"))
        self.combo_source.setItemText(0, _translate("MainWindow", "百度"))
        self.btn_saveKeyword.setText(_translate("MainWindow", "保存设置"))
        self.btn_search_link.setText(_translate("MainWindow", "通过搜索列表获取数据"))
        self.txt_pattern.setPlaceholderText(_translate("MainWindow", "结果匹配列表"))
        self.txt_keyword_flag.setPlaceholderText(_translate("MainWindow", "和搜索关键词一起作为搜索条件"))
        self.txt_keyword.setPlaceholderText(_translate("MainWindow", "请输入搜索关键词"))
        self.title_keyword.setText(_translate("MainWindow", "搜索关键词"))
        self.title_keywordFlag.setText(_translate("MainWindow", "附加关键词"))
        self.combo_pattern.setItemText(0, _translate("MainWindow", "排除"))
        self.combo_pattern.setItemText(1, _translate("MainWindow", "包含"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

